[package]
name = "actix-web-opentelemetry"
version = "0.1.0"
authors = ["Julian Tescher <julian@outtherelabs.com>"]
description = "OpenTelemetry integration for Actix Web apps"
homepage = "https://github.com/OutThereLabs/actix-web-opentelemetry"
repository = "https://github.com/OutThereLabs/actix-web-opentelemetry"
readme = "README.md"
categories = ["development-tools::debugging"]
keywords = ["actix","opentelemetry", "jaeger", "prometheus"]
license = "MIT"
edition = "2018"

[dependencies]
actix-web = "1.0.9"
futures = "0.1.25"
opentelemetry = { rev = "1c9b864c83ca962780c83db03fc072e7945d47ed", git = "https://github.com/jtescher/opentelemetry-rust" }

[dev-dependencies]
actix-rt = "0.2.6"
