[package]
name = "actix-web-opentelemetry"
version = "0.1.0"
authors = ["Julian Tescher <julian@outtherelabs.com>"]
description = "OpenTelemetry integration for Actix Web apps"
homepage = "https://github.com/OutThereLabs/actix-web-opentelemetry"
repository = "https://github.com/OutThereLabs/actix-web-opentelemetry"
readme = "README.md"
categories = ["development-tools::debugging"]
keywords = ["actix", "actix-web", "opentelemetry", "jaeger", "prometheus"]
license = "MIT"
edition = "2018"

[dependencies]
actix-web = "1.0.9"
futures = "0.1.25"
opentelemetry = "0.1.5"
regex = "1.3.1"
lazy_static = "1.4.0"

[dev-dependencies]
actix-rt = "0.2.6"
