[package]
name = "actix-web-opentelemetry"
version = "0.1.2"
authors = ["Julian Tescher <julian@outtherelabs.com>"]
description = "OpenTelemetry integration for Actix Web apps"
homepage = "https://github.com/OutThereLabs/actix-web-opentelemetry"
repository = "https://github.com/OutThereLabs/actix-web-opentelemetry"
readme = "README.md"
categories = ["development-tools::debugging"]
keywords = ["actix", "actix-web", "opentelemetry", "jaeger", "prometheus"]
license = "MIT"
edition = "2018"

[dependencies]
actix-web = "2.0.0"
futures = "0.3.4"
opentelemetry = "0.2.0"
regex = "1.3.4"
lazy_static = "1.4.0"

[dev-dependencies]
actix-rt = "1.0.0"
opentelemetry-jaeger = "0.1.0"
thrift = "0.13.0"
